// build.gradle (nivel superior)
buildscript {
    repositories {
        google()  // Asegúrate de tener este repositorio
        mavenCentral()  // O jcenter() si es necesario
    }
    dependencies {
        classpath libs.gradle  // Usa la versión apropiada
        classpath libs.google.services.v4315  // Asegúrate de la versión correcta
    }
}


// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    id 'com.google.gms.google-services' version '4.4.2' apply false
}